version: '3.1'
services:
  stats-server:
    build: stats-service/service
    image: stats-server
    container_name: stats-server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - EWM_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
    restart: on-failure

  stats-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=host
      - POSTGRES_PASSWORD=host
    restart: on-failure

  ewm-service:
    build: main-service
    image: main-server
    container_name: main-server
    depends_on:
      - ewm-db
    ports:
      - "8080:8080"
    environment:
      - EWM_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/main
    restart: on-failure

  ewm-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=host
      - POSTGRES_PASSWORD=host
    restart: on-failure